### PR TITLE
Add Spacy Syllables

### PR DESCRIPTION
**Pull request by dbirchfield80**
This extends the Spacy layer capability

### CODE REVIEW

**Comment by keithrozario** [comment]
I know it's a small thing. But would you mind removing the trailing comma and submit again.

The line shouldn't end with a comma --  might cause issues :(

**Comment by dbirchfield80** [comment]
Of course - done!

Thank you for your great work to maintain this project!
On 2/6/2021 2:39:53 AM, Keith Rozario <notifications@github.com> wrote:
I know it's a small thing. But would you mind removing the trailing comma and submit again.
The line shouldn't end with a comma -- might cause issues :(

**Comment by keithrozario** [comment]
Thanks.

LGTM & Merged :)

**Comment by keithrozario** [comment]
oops, I forgot to merge -- merged now.

**Pull request merged**
