### PR TITLE
Added awswrangler for python 3.12

### PR DESCRIPTION
**Pull request by david-fortini**

### CODE REVIEW

**Comment by keithrozario** [comment]
I think we tried this before, but it won't fit into a layer. Let's see .....

**Comment by david-fortini** [comment]
You are right, it is not displayed here [list-layers-api](https://api.klayers.cloud/api/v2/p3.12/layers/latest/eu-central-1/html )

**Comment by dschmitz89** [comment]
AWS publish layers themselves: https://aws-sdk-pandas.readthedocs.io/en/stable/layers.html

**Comment by keithrozario** [comment]
Thanks @dschmitz89, indeed that's the best source. I'm contemplating just including these layers in the API, so folks know where to get them from as well.

**Comment by david-fortini** [comment]
@keithrozario yes I think that would be very useful.

**Pull request merged**
