### PR TITLE
Added Opencv-python and imutils to P312

### PR DESCRIPTION
**Pull request by pb36**

### CODE REVIEW

**Review by keithrozario — COMMENTED** [review]
LGTm.

**Comment by keithrozario** [comment]
Thanks. Should build now. And be ready in about 15 minutes. Unless there's an issue in the build ... :)

**Comment by pb36** [comment]
@keithrozario something seems to be wrong, I can see imutils but opencv-python does not seem to be available

**Comment by keithrozario** [comment]
I think opencv-python probably failed to build :(

Will troubleshoot later, but that's most likely the case.

**Comment by Duskraelea** [comment]
sorry to reopen the thread but is opencv available on p312 or not? I saw the package is added in csv but no arn was present.

**Pull request merged**
