### PR TITLE
Add pdf2image, Spire.Doc and Spire.Xls as packages

### PR DESCRIPTION
**Pull request by D-Abdi**
Hi,

I requested a few packages that I have had some trouble with getting it to work in my Lambda function. If you could add support for these that would be great!

Ps: Love your work!

### CODE REVIEW

**Comment by keithrozario** [comment]
Thanks for contributing.

But the format of the excel is wrong, each Python package should be on it's own line of the CSV. i.e. only one package per line, if you wish to add more than one package -- you can add more lines.

Also I'm not sure what spire.doc or spire.xls are -- are they python packages available on PyPi?

**Comment by D-Abdi** [comment]
> Thanks for contributing.
> 
> But the format of the excel is wrong, each Python package should be on it's own line of the CSV. i.e. only one package per line, if you wish to add more than one package -- you can add more lines.
> 
> Also I'm not sure what spire.doc or spire.xls are -- are they python packages available on PyPi?

Hi, 

Thank you for the heads-up. I have mutated the CSV to have each package on a separate line.
Also, yes spire.doc and spire.xls are python packages available PyPi that are used to accomplish a similar goal to pdf2image but for the files with a doc, docx, xls and xlsx format.

**Comment by keithrozario** [comment]
almost there ... each line is 3 columns (so we need 3 commas), and the email is the contact of the author.

**Comment by keithrozario** [comment]
sorry to be pedantic, but if the format of the file is wrong, the entire pipeline might fail :(

**Pull request closed without merging**
