### PR TITLE
Add pandasql and duckdb packages for python3.12

### PR DESCRIPTION
**Pull request by LyleMartin**

### CODE REVIEW

**Comment by keithrozario** [comment]
Pandassql didn't work for some reason. But duckdb was successful.

arn:aws:lambda:af-south-1:770693421928:layer:Klayers-p312-duckdb:1

**Comment by LyleMartin** [comment]
Thank you so much! Sent from my Verizon, Samsung Galaxy smartphone
-------- Original message --------From: Keith Rozario ***@***.***> Date: 6/15/24  4:41 AM  (GMT-05:00) To: keithrozario/Klayers ***@***.***> Cc: LyleMartin ***@***.***>, Author ***@***.***> Subject: Re: [keithrozario/Klayers] Add pandasql and duckdb packages for
  python3.12 (PR #419) 
Pandassql didn't work for some reason. But duckdb was successful.
arn:aws:lambda:af-south-1:770693421928:layer:Klayers-p312-duckdb:1

**Comment by LyleMartin** [comment]
Thank you. When I add the library I get no responses from the Lambda function. I have an exception set up to to SNS but also a dead letter queue. So usually on exception I get a message.  

I tried changing the order of the import calls, and the order of merging the libraries and still nothing. Only if I take layer out do I get an error that the module could not be imported.  

When I use your layers for pandas, numpy and now duckdb it goes over the size limit. When I use the AWS layer for pandas and your layer for duckdb it fits in the limit. But when I run the code I get no response at all -- no exception, no results.  No logging either, so I know it is dying. 

I am at a loss. I don't want to go to containers. Any thoughts are greatly appreciated. 

Thanks, 

-Lyle

----------------------------------------

**Comment by keithrozario** [comment]
Oh, one more thing. If nothing works try importing duckdb within your function handler -- instead of before it. This forces it to run during runtime instead of init time. And that might help.

**Comment by LyleMartin** [comment]
Thank you 

----------------------------------------

**Pull request merged**
